// Auto-generated Svelte wrapper components for Maxzilla UI
// Do not edit this file directly - use npm run generate to regenerate

// Import web components to ensure they are registered
import '@maxzilla/ui-core';

// Component exports
export { default as Button } from './lib/Button.svelte';
export { default as Card } from './lib/Card.svelte';
export { default as Input } from './lib/Input.svelte';
export { default as Badge } from './lib/Badge.svelte';
export { default as Avatar } from './lib/Avatar.svelte';
export { default as Modal } from './lib/Modal.svelte';

// Type definitions
export interface ButtonProps {
  variant?: 'primary' | 'secondary' | 'outline' | 'ghost' | 'danger';
  size?: 'sm' | 'md' | 'lg';
  loading?: boolean;
  disabled?: boolean;
  href?: string;
  target?: string;
  rel?: string;
  type?: 'button' | 'submit' | 'reset';
}

export interface CardProps {
  elevation?: 'none' | 'sm' | 'md' | 'lg' | 'xl';
  clickable?: boolean;
}

export interface InputProps {
  label?: string;
  type?: string;
  value?: string;
  placeholder?: string;
  disabled?: boolean;
  required?: boolean;
  readonly?: boolean;
  helperText?: string;
  name?: string;
  min?: string;
  max?: string;
  step?: string;
}

export interface BadgeProps {
  variant?: 'success' | 'warning' | 'error' | 'info';
  size?: 'sm' | 'md' | 'lg';
}

export interface AvatarProps {
  src?: string;
  alt?: string;
  size?: 'sm' | 'md' | 'lg';
  online?: boolean;
}

export interface ModalProps {
  open?: boolean;
  size?: 'sm' | 'md' | 'lg';
}
