// Auto-generated React wrapper components for Maxzilla UI
// Do not edit this file directly - use npm run generate to regenerate

export { useWebComponents } from './utils/createReactWrapper.js'

export { Button, type ButtonProps } from './components/Button.js'
export { Card, type CardProps } from './components/Card.js'
export { Input, type InputProps } from './components/Input.js'
export { Badge, type BadgeProps } from './components/Badge.js'
export { Avatar, type AvatarProps } from './components/Avatar.js'
export { Modal, type ModalProps } from './components/Modal.js'