// Auto-generated Vue wrapper components for Maxzilla UI
// Do not edit this file directly - use npm run generate to regenerate

// Import web components to ensure they are registered
import '@maxzilla/ui-core'

// Component exports
export { default as MzButton } from './components/MzButton.vue'
export { default as MzCard } from './components/MzCard.vue'
export { default as MzInput } from './components/MzInput.vue'
export { default as MzBadge } from './components/MzBadge.vue'
export { default as MzAvatar } from './components/MzAvatar.vue'
export { default as MzModal } from './components/MzModal.vue'

// Type exports  
export type { ButtonProps } from './components/MzButton.vue'
export type { CardProps } from './components/MzCard.vue'
export type { InputProps } from './components/MzInput.vue'
export type { BadgeProps } from './components/MzBadge.vue'
export type { AvatarProps } from './components/MzAvatar.vue'
export type { ModalProps } from './components/MzModal.vue'

// Plugin for global registration
import type { App } from 'vue'
import MzButton from './components/MzButton.vue'
import MzCard from './components/MzCard.vue'
import MzInput from './components/MzInput.vue'
import MzBadge from './components/MzBadge.vue'
import MzAvatar from './components/MzAvatar.vue'
import MzModal from './components/MzModal.vue'

export default {
  install(app: App) {
    app.component('MzButton', MzButton)
    app.component('MzCard', MzCard)
    app.component('MzInput', MzInput)
    app.component('MzBadge', MzBadge)
    app.component('MzAvatar', MzAvatar)
    app.component('MzModal', MzModal)
  }
}
